### ISSUE TITLE
Section for CFPs?

### ISSUE THREAD

**Issue by karllhughes** [devrelcollective/awesome-devrel#11]
Just curious, but is there any interest in adding a list of resources for finding and submitting CFPs to conferences? This seems to be a pretty common task for DevRels, and I've got a big list of resources I'd be happy to add. Just didn't want to step on any toes as it's my first contribution to this repo.

Thanks!

**Comment by mbbroberg** [comment]
@karllhughes that sounds like a great idea, your contribution is quite welcome. Feel free to add a new header for it as well.

**Comment by mbbroberg** [comment]
Closed by #12
