### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by mhall119** [devrelcollective/awesome-devrel#40]
The LICENSE.md in the root of the repo is CC BY-NC-SA, but the README.md has a License section that says it's CC BY. 

However, the License section is a sub-heading under Events, so it's unclear if that applies to the whole document or just the Youtube channel linked above it.

**Comment by davidgs** [comment]
@jerdog maybe you have some insight into the licensing?

**Comment by jerdog** [comment]
Ok - great catch @mhall119. So CC BY-NC-SA doesn't apply for this, because most of the ideas, suggestions, etc. are all going to be used for commercial. I'll adjust.

The License section under Events is a mistake - the license should be a main heading. I'll fix as well.
