### ISSUE TITLE
CommonRoom

### ISSUE THREAD

**Issue by hhkaos** [devrelcollective/awesome-devrel#59]
I just found this tool and looks pretty interesting:
https://www.commonroom.io/

I'm on my phone, so I can't do the PR now but I don't want to miss the opportunity to suggest it here at least: https://www.commonroom.io/

**Comment by hhkaos** [comment]
Related: https://github.com/orbit-love/orbit-model & https://orbit.love/ :)

**Comment by RCheesley** [comment]
Just pending changes on https://github.com/devrelcollective/awesome-devrel/pull/60.
