### ISSUE TITLE
Hashnode is mentioned twice

### ISSUE THREAD

**Issue by rwiteshbera** [devrelcollective/awesome-devrel#68]
Hashnode is mentioned twice in the `Websites to Publish Articles` section.

<img src="https://user-images.githubusercontent.com/73098407/235365406-b8828e44-9dd9-4c67-8b6e-d1fd427f087e.png" height="400" />

**Comment by jerdog** [comment]
Hey @rwiteshbera sorry for the delay. Want to submit a PR and I'll merge it?

**Comment by shrirajpawar4** [comment]
@jerdog submitted a Pr for same.

**Comment by jerdog** [comment]
Fixed with #73
